name: rinalmo
channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - appdirs=1.4.4=pyh9f0ad1d_0
  - biopython=1.81=py311h459d7ec_1
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - bleach=6.1.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py311hb755f60_1
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2024.2.2=hbcca054_0
  - cd-hit=4.8.1=h43eeafb_9
  - certifi=2024.2.2=pyhd8ed1ab_0
  - charset-normalizer=3.3.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - docker-pycreds=0.4.0=py_0
  - filelock=3.12.4=pyhd8ed1ab_0
  - fsspec=2023.9.2=pyh1a96a4e_0
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.40=pyhd8ed1ab_0
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py311h6a5fa03_1
  - icu=73.2=h59595ed_0
  - idna=3.4=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - kaggle=1.5.16=pyhd8ed1ab_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.8.0.34=0
  - libcurand=10.3.4.52=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libgomp=13.2.0=h807b86a_2
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hd590300_0
  - libnvjpeg=11.9.0.86=0
  - libprotobuf=4.24.4=hf27288f_0
  - libsqlite=3.43.2=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libuuid=2.38.1=h0b41bf4_0
  - libxml2=2.11.5=h232c23b_1
  - libzlib=1.2.13=hd590300_5
  - lightning=2.2.0.post0=pyhd8ed1ab_0
  - lightning-utilities=0.10.1=pyhd8ed1ab_0
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=2.1.3=py311h459d7ec_1
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.0=hb012696_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - ncurses=6.4=hcb278e6_0
  - networkx=3.2=pyhd8ed1ab_1
  - numpy=1.26.0=py311h64a7726_0
  - openssl=3.2.1=hd590300_0
  - packaging=23.2=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - pip=23.3=pyhd8ed1ab_0
  - protobuf=4.24.4=py311h46cbc50_0
  - psutil=5.9.5=py311h459d7ec_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.5=hab00c5b_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-lmdb=1.4.1=py311h8731a88_1
  - python-slugify=8.0.1=pyhd8ed1ab_2
  - python_abi=3.11=4_cp311
  - pytorch=2.1.0=py3.11_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-lightning=2.1.3=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py311h459d7ec_1
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - sentry-sdk=1.32.0=pyhd8ed1ab_0
  - seqkit=2.5.1=h9ee0642_0
  - setproctitle=1.3.3=py311h459d7ec_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - sympy=1.12=pypyh9d50eac_103
  - tbb=2021.10.0=h00ab1b0_2
  - text-unidecode=1.3=pyhd8ed1ab_1
  - tk=8.6.13=h2797004_0
  - torchmetrics=1.2.1=pyhd8ed1ab_0
  - torchtriton=2.1.0=py311
  - tqdm=4.66.1=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - urllib3=2.0.7=pyhd8ed1ab_0
  - wandb=0.15.12=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - wheel=0.41.2=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.13=hd590300_5
  - pip:
      - absl-py==2.0.0
      - contextlib2==21.6.0
      - einops==0.7.0
      - flash-attn==2.3.2
      - joblib==1.3.2
      - ml-collections==0.1.1
      - ninja==1.11.1.1
      - pandas==2.1.1
      - pytz==2023.3.post1
      - scikit-learn==1.3.1
      - scipy==1.11.3
      - threadpoolctl==3.2.0
      - tzdata==2023.3
